# Generated by Django 5.0 on 2025-11-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('beverage', 'Beverage'), ('food', 'Food'), ('merchandise', 'Merchandise'), ('other', 'Other')], default='beverage', max_length=20),
        ),
    ]
